-- 001_init_apollo_schema.sql
-- Migracja bazowa: tworzy model danych dla synchronizacji Apollo outreach analytics.
-- Schema: apollo | Tabele: sequences, contacts, outreach_messages
-- Idempotentna (IF NOT EXISTS) - bezpieczna do wielokrotnego uruchomienia.

-- ============================================================
-- SCHEMA
-- ============================================================
CREATE SCHEMA IF NOT EXISTS apollo;

-- ============================================================
-- SEQUENCES (Apollo campaign sequences)
-- ============================================================
CREATE TABLE IF NOT EXISTS apollo.sequences (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apollo_sequence_id  TEXT NOT NULL UNIQUE,
    sequence_name       TEXT NOT NULL,
    campaign_slug       TEXT,
    campaign_type       TEXT,
    persona             TEXT,
    industry            TEXT,
    owner_email         TEXT,
    status              TEXT,
    created_at          TIMESTAMPTZ,
    updated_at          TIMESTAMPTZ,
    inserted_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- CONTACTS (Apollo contacts / recipients)
-- ============================================================
CREATE TABLE IF NOT EXISTS apollo.contacts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apollo_contact_id   TEXT NOT NULL UNIQUE,
    email               TEXT,
    full_name           TEXT,
    company_name        TEXT,
    title               TEXT,
    persona_bucket      TEXT,
    industry_bucket     TEXT,
    inserted_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- OUTREACH MESSAGES (individual emails sent via Apollo)
-- ============================================================
CREATE TABLE IF NOT EXISTS apollo.outreach_messages (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apollo_message_id   TEXT NOT NULL UNIQUE,
    apollo_sequence_id  TEXT,
    apollo_contact_id   TEXT,
    mailbox_user        TEXT,
    subject             TEXT,
    step_number         INTEGER,
    sent_at             TIMESTAMPTZ,
    status              TEXT,
    reply_type          TEXT,
    is_delivered        BOOLEAN,
    is_opened           BOOLEAN,
    is_clicked          BOOLEAN,
    is_replied          BOOLEAN,
    is_positive_reply   BOOLEAN,
    is_unsubscribed     BOOLEAN,
    is_bounced          BOOLEAN,
    is_spam_blocked     BOOLEAN,
    raw_payload         JSONB,
    inserted_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- INDEXES on outreach_messages
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_outreach_messages_sequence_id
    ON apollo.outreach_messages (apollo_sequence_id);

CREATE INDEX IF NOT EXISTS idx_outreach_messages_contact_id
    ON apollo.outreach_messages (apollo_contact_id);

CREATE INDEX IF NOT EXISTS idx_outreach_messages_sent_at
    ON apollo.outreach_messages (sent_at);

CREATE INDEX IF NOT EXISTS idx_outreach_messages_status
    ON apollo.outreach_messages (status);

CREATE INDEX IF NOT EXISTS idx_outreach_messages_reply_type
    ON apollo.outreach_messages (reply_type);
